server:
  port: 8080

spring:
  application:
    name: banking-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL}/bank
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

build:
  group: '@project.groupId@'
  artifact: '@project.artifactId@'
  version: '@project.version@'

bank:
  name: my-bank
